// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkJmWQEhui9FiKEwJyiBkDYzJgUGWj7sQ',
    appId: '1:1021784629235:web:bc7ffe7cc7e7109bc63c86',
    messagingSenderId: '1021784629235',
    projectId: 'blood-bank-app-986a4',
    authDomain: 'blood-bank-app-986a4.firebaseapp.com',
    storageBucket: 'blood-bank-app-986a4.firebasestorage.app',
    measurementId: 'G-YM406CBG9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRUDrB7qhcd18YUZ_Q284ONIy50QCTTsw',
    appId: '1:1021784629235:android:9bf283beb2be7507c63c86',
    messagingSenderId: '1021784629235',
    projectId: 'blood-bank-app-986a4',
    storageBucket: 'blood-bank-app-986a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVIP6meVnFOZ1JCKfsMFZWdMHngWIUjJA',
    appId: '1:1021784629235:ios:70e041631249f875c63c86',
    messagingSenderId: '1021784629235',
    projectId: 'blood-bank-app-986a4',
    storageBucket: 'blood-bank-app-986a4.firebasestorage.app',
    iosBundleId: 'com.example.bloodBankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVIP6meVnFOZ1JCKfsMFZWdMHngWIUjJA',
    appId: '1:1021784629235:ios:70e041631249f875c63c86',
    messagingSenderId: '1021784629235',
    projectId: 'blood-bank-app-986a4',
    storageBucket: 'blood-bank-app-986a4.firebasestorage.app',
    iosBundleId: 'com.example.bloodBankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkJmWQEhui9FiKEwJyiBkDYzJgUGWj7sQ',
    appId: '1:1021784629235:web:c514b3d5dd6927b6c63c86',
    messagingSenderId: '1021784629235',
    projectId: 'blood-bank-app-986a4',
    authDomain: 'blood-bank-app-986a4.firebaseapp.com',
    storageBucket: 'blood-bank-app-986a4.firebasestorage.app',
    measurementId: 'G-XLNNCJ6G7R',
  );
}
